### PR TITLE
Tschopp01

### PR DESCRIPTION
**Pull request by tschopp**

### CODE REVIEW

**Comment by tschopp** [comment]
hope I didn't mess it up

**Comment by tschopp** [comment]
did it work?

**Comment by krashanoff** [comment]
It worked! The only thing I stepped in to resolve was a very small conflict.

**Comment by tschopp** [comment]
Tell me what conflict you had to resolve?  And you get notification of all
changes I make?  I've done a lot of website dev, but new to Github.

Thanks, Todd

**Pull request merged**
